name: Doc Generation

on: [push, pull_request]

jobs:
  MasterDoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          bash ./.github/scripts/install_libiio.sh
          pip install -r requirements_doc.txt
      - name: Build doc and release
        run: |
          cd docs && mkdir devices
          python parse_context_files.py
          cd ..
          mkdocs build
      - name: Publish doc
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          destination_dir: master
