name: Doc Generation

on: [push, pull_request]

jobs:
  MasterDoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          bash ./.github/scripts/install_libiio.sh
          pip install -r requirements_doc.txt
          pip install .

      - name: Build docs
        run: |
          cd docs && mkdir -p devices
          python parse_context_files.py
          cd ..
          sphinx-build -b html docs docs/_build/html

      - name: Publish doc
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          destination_dir: master
